module.exports = {
    USER_LOGIN:"USER_LOGIN",
    USER_DISCONNECTED: "USER_DISCONNECTED",
    MESSAGE_SENT: "MESSAGE_SENT",
    MESSAGE_RECIEVED: "MESSAGE_RECIEVED",
    SEND_MESSAGE_PRIVATE: "SEND_MESSAGE_PRIVATE",
    RECIEVE_MESSAGE_PRIVATE: "RECIEVE_MESSAGE_PRIVATE",
    SEND_CHAT_STATE: "SEND_CHAT_STATE",
    USER_LOGOUT: "USER_LOGOUT",
    VERIFY_USER: "VERIFY_USER",
    SEND_USER_DATA:"SEND_USER_DATA",
    NEW_USER: "NEW_USER",
}